### PR TITLE
update to react 16

### PR DESCRIPTION
**Pull request by animesh10**
Updates for React16.

### CODE REVIEW

**Comment by ajoshi0** [comment]
@kenwheeler and @ryan-roemer please check this another pr for react-16 upgrade. Already tested on our side with this code changes. If any issues please let us know

**Comment by ryan-roemer** [comment]
@animesh10 @ajoshi0 -- Thanks for the work. I'll take it from here -- this is missing `prop-types` dep and some other things I'm directly fixing.

**Comment by ryan-roemer** [comment]
Released in `radon-select@3.0.0` (with a now much slimmer npm package). Let me know if y'all hit snags...

**Comment by ajoshi0** [comment]
thanks @ryan-roemer will check and update

**Pull request merged**
